/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/EventCard`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/FavoriteButton`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/src/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/src/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/CreateEventScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/DashboardScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/EditEventScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/FavoriteEventsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/SignInScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/services/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/validationSchemas`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/EventCard`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/FavoriteButton`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/Header`; params?: Router.UnknownOutputParams; } | { pathname: `/src/context/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/src/navigation/AppNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/CreateEventScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/DashboardScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/EditEventScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/FavoriteEventsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/SignInScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/SignUpScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/src/services/firebaseConfig`; params?: Router.UnknownOutputParams; } | { pathname: `/src/utils/validationSchemas`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/src/components/EventCard${`?${string}` | `#${string}` | ''}` | `/src/components/FavoriteButton${`?${string}` | `#${string}` | ''}` | `/src/components/Header${`?${string}` | `#${string}` | ''}` | `/src/context/AuthContext${`?${string}` | `#${string}` | ''}` | `/src/navigation/AppNavigator${`?${string}` | `#${string}` | ''}` | `/src/screens/CreateEventScreen${`?${string}` | `#${string}` | ''}` | `/src/screens/DashboardScreen${`?${string}` | `#${string}` | ''}` | `/src/screens/EditEventScreen${`?${string}` | `#${string}` | ''}` | `/src/screens/FavoriteEventsScreen${`?${string}` | `#${string}` | ''}` | `/src/screens/SignInScreen${`?${string}` | `#${string}` | ''}` | `/src/screens/SignUpScreen${`?${string}` | `#${string}` | ''}` | `/src/services/firebaseConfig${`?${string}` | `#${string}` | ''}` | `/src/utils/validationSchemas${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/EventCard`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/FavoriteButton`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/src/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/src/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/CreateEventScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/DashboardScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/EditEventScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/FavoriteEventsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/SignInScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/services/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/validationSchemas`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
